service: levis-be
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1

functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - http:
          path: serverlessSetup/hello
          method: get
  goodbye:
    handler: src/functions/goodbye.handler
    events:
      - http:
          path: serverlessSetup/goodbye
          method: post

plugins:
  - serverless-plugin-typescript

resources:
