service: levis-be
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1

functions:
  agendas:
    handler: src/agenda/controller/agenda.handler
    events:
      - http:
          path: api/agendas
          method: get
  agendamento:
    handler: src/agendamento/controller/agendamento.handler
    events:
      - http:
          path: api/agendamento
          method: post

plugins:
  - serverless-offline

package:
  patterns:
    - '!src/_tests_/**'

resources:
